### ISSUE TITLE
The disregard mechanism is undocumented

### ISSUE THREAD

**Issue by bbottema** [chrisvest/stormpot#117]
I couldn't find any documentation on the disregard mechanism, but it is making BlazePool somewhat unpredictable, as any object that ends up in there gets treated differently from the rest of the pool. Say I'm doing my own object tracking an allocator (like counting live objects), this might not reflect what BlazePool actually thinks (related to #115).

I suspect it is a performance optimization, but I couldn't find any documentation on it and I couldn't really glance from the code how it is supposed to work.

**Comment by chrisvest** [comment]
It's important for avoid busy looping in claim. TLR-claimed slots will be present in the live queue but can neither be claimed nor really removed from the live queue, yet we want to use the blocking methods of the queue for waiting. We use the disregard pile to temporarily stow away the TLR claimed slots.

Obviously, background expiration checking should be aware of this and not forget about stowed slots. This is fixed in https://github.com/chrisvest/stormpot/commit/b9b48ed7f88a54d082b1dc50d8e1fa3804322f77
