### ISSUE TITLE
Proactive validation on idle

### ISSUE THREAD

**Issue by simongibbs** [chrisvest/stormpot#68]
I would like to have the Pool call the Expiration to revalidate the Poolable at regular intervals when the pool is idle.

For bonus karma, being able to a pass suggested validation time to the Pool as a "delay until after" value.  In effect, I would be saying "check this again in a minute".

```
public Timeout mustRevalidate(Slot slot);
```

Revalidation might occur after a dead poll has timed out on the allocator thread, and if the advised timeout has elapsed and while the pool is otherwise full and healthy.

A sensible time to call mustRevalidate might be after a Pooleable is allocated or released.

**Comment by simongibbsft** [comment]
The only constraint that makes sense to me is that the revalidation frequency is bounded by a minimum interval. This could reasonably control only the pro-active validations and not interact with validations on claim (though, equally, that would be nice). So I think what you are proposing would be perfectly fine, although the link does not work for me.

#68 is still a feature that we would value.

**Comment by chrisvest** [comment]
@simongibbsft I have since merged in and removed that branch. You can see the main commit here: https://github.com/chrisvest/stormpot/commit/0104fe2dc9d8c8dbe7eb20be4d8d6ff3cad63d48

So this is actually already a part of the 2.3 release: https://medium.com/@chrisvest/released-stormpot-2-3-684b730f9d1b

I might have forgotten to write to the mailing list, though. I don't remember.
