### ISSUE TITLE
Poolable release vs close

### ISSUE THREAD

**Issue by rdifalco** [chrisvest/stormpot#89]
I'm trying to create an pool-agnostic poolable resource and one thing I bump into that is not a big issue, but kinda ugly, is that Poolable defines release vs. close. Personally, I would like it if Poolable implemented AutoClosable with #close instead of #release. I'm not sure if there was a reason for this or if it is just legacy but it seems like if you are pooling Database Connections, Sockets, Files, or Redis Clients, you are going to want to have the typical #close method delegate to your #release.

Not a big deal, and I wouldn't want you to break backwards compatibility but I just thought I'd mention it.

**Comment by chrisvest** [comment]
@rdifalco I'm thinking this might not be such a good idea after all, because `claim` returns `null` if it times out, in which case you'll get an NPE.

Since I plan on moving to Java 8 for 3.0, I think it'd be better to add a method to the pools that take a lambda, and pass a poolable to the lambda if the claim succeeds, or returns some boolean signal if the claim fails.

**Comment by chrisvest** [comment]
Started here: f6d3893b88a45873c04b69967ae074383af06a9a

**Comment by chrisvest** [comment]
I think this is done with 378ff674eccc33a3653a60bb77656587b60d9b85
