### ISSUE TITLE
Asynchronous Clock Source

### ISSUE THREAD

**Issue by chrisvest** [chrisvest/stormpot#92]
Allow the time-based expirations to use a clock-source that is just a volatile field, which is updated asynchronously by the allocator thread. This way, getting the time is just a volatile field read. Such a clock source is a lot more fuzzy with how accurately it updates, but it should be good enough for our case where expiration times are usually measured in minutes.

This may require MethodHandles, so the feature can be enabled/disabled at runtime while still being very fast and optimise well in the common case. Hence 3.0.

**Comment by jentfoo** [comment]
I have this in my project actually, you might want to check it out:

https://github.com/threadly/threadly/blob/master/src/main/java/org/threadly/util/Clock.java

I of course do not think you would want to depend on threadly for such a trivial concept (though you might find other aspects useful as well).  But you should check out the usage of it internally.  You will see we are able to optimize out a lot of system clock calls because often times the fuzzy time can provide a "good enough" time to make a decision if something should happen or not.

**Comment by chrisvest** [comment]
The only difficult part of this idea is the life cycle around who's in charge of updating the clock. This is stuck behind the work on background process control for this reason.

**Comment by jentfoo** [comment]
> The only difficult part of this idea is the life cycle around who's in charge of updating the clock

In the threadly clock class by default we start a thread which will wakeup every 100 milliseconds.  If the clock has not been updated from some other source (a source needing more accuracy for one reason or another), then it will take that opportunity to update it.

That way, the last known time is at most inaccurate to 100 milliseconds (assuming that the thread to update it gets some CPU time from the scheduler), and _may_ be more accurate than that.  If that is not good enough you can go directly to accurate time and hopefully benefit some other thread using the last known reference.

Because threadly has lots of activities where we need to see if they are "ready to run", we can optimistically try to use the last known time, and if they are not ready only then force a clock update to ensure we are truly not ready to run (or maybe are).

**Comment by chrisvest** [comment]
I've decided not to do this because 1) a background thread that also interacts with the allocator can have unknown variance in how often it can update the clock, and 2) it seems people are more interested in having low idle CPU usage, which again encourages a background thread that is idle whenever possible.
